---
- include_tasks: preflight.yml
  tags:
    - restic_install
    - restic_configure

- block:
  - include_tasks: install.yml
    tags:
      - restic_install
  become: true

- name: Whitelist restic to run certain commands with sudo
  template:
    src: 'restic.sudoers.j2'
    dest: "/etc/sudoers.d/restic-sudoers"
    owner: root
    group: root
    mode: '0440'
    validate: "visudo -cf %s"
  when: restic_user != 'root'
  tags:
    - restic_configure

- block:
  - include_tasks: configure_repos.yml
    with_items: '{{ restic_repos }}'
    no_log: true
    tags:
      - restic_configure
  become: true
